### ISSUE TITLE
Ask about？

### ISSUE THREAD

**Issue by badboycxcc** [b1tg/cobaltstrike-beacon-rust#1]
Is there only the cmd_shell function now?
Does the master test on multiple platforms? Win, Linux, Mac)

**Comment by b1tg** [comment]
Currently, only command execution is supported. I have developed and tested this project on Linux. It has not yet been tested on other platforms.

**Comment by 808Mak1r** [comment]
I tested it successfully on the mac platform.But windows didn't work.

**Comment by b1tg** [comment]
Windows support added after https://github.com/b1tg/cobaltstrike-beacon-rust/pull/3 by @808Mak1r

**Comment by badboycxcc** [comment]
OK, I'll test it.
