### ISSUE TITLE
Cargo.toml missing hmac

### ISSUE THREAD

**Issue by 808Mak1r** [b1tg/cobaltstrike-beacon-rust#2]
An error occurred while I was running it.
<img width="873" alt="image" src="https://github.com/b1tg/cobaltstrike-beacon-rust/assets/39427457/2652a418-3cd6-4bb9-9334-1aba201c6c02">
Use `cargo add hmac` to solve the problem.
<img width="678" alt="image" src="https://github.com/b1tg/cobaltstrike-beacon-rust/assets/39427457/6bbc529a-a481-454e-80ff-b6fbf9d989ea">

**Comment by b1tg** [comment]
Fixed in https://github.com/b1tg/cobaltstrike-beacon-rust/pull/3
