### ISSUE TITLE
Some help if you don't mind

### ISSUE THREAD

**Issue by moscowchill** [b1tg/cobaltstrike-beacon-rust#4]
starting connect to https://xxx:8080/fwlink
http error: Some(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(xx)), port: Some(8080), path: "/fwlink", query: None, fragment: None }, source: hyper::Error(Connect, Os { code: -2146762487, kind: Uncategorized, message: "A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider." }) })

I'm new to cobalt strike and only configured a listener.
And to no suprise the client doesn't want to connect.
Not really sure what else I have to do. Would you mind helping?

**Comment by moscowchill** [comment]
So yeah I'm new to CS, what I seem to be missing is a c2 profile. 
Would anyone mind sharing one that goes with this client?

**Comment by b1tg** [comment]
This seems caused by self signed certificate

change `let client = reqwest::blocking::Client::new();` to `let client = ClientBuilder::new().danger_accept_invalid_certs(true).build().unwrap();` should work
